### ISSUE TITLE
figures epower paper

### ISSUE THREAD

**Issue by isabelbrandao** [beckyfisher/epower_examples#1]
Hi Becky,

I was wondering if you could share the code and raw data you used to make figures 3 and 4 of your paper : "epower: An r package for power analysis of Before‐After‐Control‐Impact (BACI) designs". I was trying to use the pilot_data provided with epower, but I guess some data is missing there, reason why I get different results. 

Cheers,

Isabel

**Comment by beckyfisher** [comment]
Sorry for the late reply. 
The data belong to DBCA and they only agreed for me to share a single section of the data to show how to run the epower code.
